### ISSUE TITLE
Support updating test durations when running for a single group

### ISSUE THREAD

**Issue by mbkroese** [jerry-git/pytest-split#11]
It would be useful to add support for calculating test durations while using the parameters `--splits` and `group`. To clarify, this is currently possible but it runs the full test suite, not just the tests for that particular group. Instead, users can calculate the test_durations for each group and then combine the results.

Happy to send a merge request your way if you think this makes sense!

**Comment by jerry-git** [comment]
Interesting and good idea 👍  How would it actually work? Each `pytest --splits ...` process could generate a file containing the durations for the tests ran in that group but what kind of magic would combine those or would that be a manual process?

**Comment by mbkroese** [comment]
I'm afraid that would indeed be a manual process for now.
Each group would create its own test_durations file and in a later step these files are merged into one.

With the current format of storing execution times (JSON) it's a bit hard to combine the results since they are not easy to concatenate. However, by changing the format to CSV appending becomes trivial:

```
cat *.csv > test_durations.csv
```

What do you think?

**Comment by jerry-git** [comment]
I guess we could provide some simple command which would combine the reports, e.g. `coverage` has [combine](https://coverage.readthedocs.io/en/v4.5.x/cmd.html#combining-data-files). Then it could do its magic using Python and the user would not need to know how it's done. And json files would do just fine.

**Comment by mbkroese** [comment]
Yes I'm aware of `coverage combine`.
I think the difference is that `coverage` is its own application  whereas `pytest-splits` is a plugin and I'm not sure if the user woud expect a plugin for `pytest` to instal an additional command line tool. This command line tool would also have only one command:  `pytest-splits combine`.

In my opinion appending files is slightly preferred because the `cat` command I shared above is simple and uses standard tools available on almost all machines.

I'll you decide :)

**Comment by jerry-git** [comment]
> pytest-splits is a plugin and I'm not sure if the user woud expect a plugin for pytest to instal an additional command line tool.

I don't think it's a biggie. For example, `pytest-cov` depends on `coverage` and thus installing `pytest-cov` makes `coverage` CLI command available.

I just don't like that the user should know how the "internals" of `pytest-split` work, which is why I'd prefer a custom command 🙂  And the duration files for individual groups could go for example to _.pytest_split_ or _.test_durations_ directory.

**Comment by sondrelg** [comment]
I think just writing new results to the existing file makes the most sense. This would let users decide how they combine and/or manage their test-duration file.

Here's what I would like it to look like:

```yaml
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Load test durations file from cache
      - uses: actions/cache@v2
        with:
          path: .test_durations
          key: 0  # doesn't matter
          restore-keys: 0  # doesn't matter
      
      # Run tests
      - run: pytest --splits 8 --group ${{ matrix.group }} --store-durations
    
      # If .test_durations was found in the cache, then the plugin would write to the existing file
      # If the cache was empty, it would create a new file with data from the tests run
      # In both cases the cache will store the file for next time
```

There are a few things to consider though:

1. I think the current file format might not make the most sense. I guess ordering the tests by duration is important for the core split logic, but I think it might make more sense to store the results as a dict. That would make writing new entries and/or updating entries much easier, wouldn't it?

2. I think it might make sense to allow the user to have no test-durations file at all. I know you assume a mean runtime for undocumented tests - maybe you could extend the logic to assume an equal (the number doesn't matter) runtime if no file exists, so that the first split just splits by number of tests. It wouldn't be perfect, but it would save users from ever needing to worry about test duration mapping. The test suite would just be improved with each run automatically.

3. You don't need to write to `.pytest_split` or `.test_durations`. You might be well aware of this, but just in case you're not, pytest provides a way to write to the pytest cache in the [config](https://github.com/jerry-git/pytest-split/blob/master/src/pytest_split/plugin.py#L46) object, like [this](https://github.com/pytest-dev/pytest/blob/main/src/_pytest/cacheprovider.py#L396). Writing to `.test_durations` makes sense if you want users to commit the timing data to version control, but ideally I would like to just cache my whole `.pytest_cache` between runs and let it update itself.

If we wanted to do all three, you could also remove the `--store-durations` flag and make writing to the cache the default behavior. That would leave new users only needing to add this to their workflow to reap all the benefits it brings:

```yaml
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v2
        with:
          path: .pytest_cache
          key: 
          restore-keys: 
      # pytest-split is enabled if `splits` and `group` is found, 
      # and writes to `.pytest_cache/v/cache/pytest_splits` automatically
      - run: pytest --splits 8 --group ${{ matrix.group }}
```

And then each run would get a little bit more accurate 🙂 

Sorry for the block of text; hope some of it made sense. Looking forward to hearing your thoughts - I've probably definitely forgotten to consider some things 👍
